services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
          DB_HOST: database
          DB_NAME: "${POSTGRES_DB}"
          DB_USER: "${POSTGRES_USER}"
          DB_PASS: "${POSTGRES_PASSWORD}"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    env_file:
      - ./.env
  
  database:
    image: postgres:14.6-alpine
    environment:
          POSTGRES_DB: "${POSTGRES_DB}"
          POSTGRES_USER: "${POSTGRES_USER}"
          POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"