# Generated by Django 3.2.16 on 2023-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230811_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='full_price',
            field=models.PositiveIntegerField(),
        ),
    ]
